### ISSUE TITLE
使用例のjavascriptでの使い方のソースコードを記載して欲しい

### ISSUE THREAD

**Issue by minmin0530** [digital-go-jp/design-tokens#98]
使用例のCSSは期待通りの結果を試すことができました。
使用例のjavascriptは期待通りの結果を試すことが困難でした。
Reactのコンポーネントで使用しているthemePluginの使い方、もしくはjavascript/HTMLで使用しているthemePluginの使い方を記載していただきたいです。

**Comment by johnykei** [comment]
@minmin0530 様

コメント頂きありがとうございます。

Tailwind Theme Plugin を見て頂くとデザイントークンがどのように利用されているかが分かるため、
もしご興味がございましたら、[Tailwind Theme Pluginのリポジトリ](https://github.com/digital-go-jp/tailwind-theme-plugin)をご参照ください。

また、大変申し訳ございませんが、現状こちらのリポジトリではサンプルコードの追加予定はございません。
（将来的には追加の可能性はございます。）

こちらのIssueについてはクローズさせていただきます。

改めてコメント頂きありがとうございました。
